### ISSUE TITLE
Technologies to be used

### ISSUE THREAD

**Issue by KKucharczyk** [KKucharczyk/Chat-app#1]
It should be decided, what technology should we work in.

**Comment by kret11** [comment]
Technology stack for backend:
- Heroku as hosting and www service
- Tomcat as application server
- Java Enterprise Edition 8:
   - Servlets with Websocket service
   - some additional libraries (eg. spatial)

**Comment by KKucharczyk** [comment]
Technology for application:
- ide: Android Studio
- Java 8
- Gradle
- jUnit 4

Test units:
- Sony Xperia Z5 Compact
- Sony Xperia L
- Android Virtual Device
